"""updated image teacher and student

Revision ID: 093d744e71aa
Revises: b9903aa4ce8e
Create Date: 2025-03-04 16:04:37.434550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '093d744e71aa'
down_revision: Union[str, None] = 'b9903aa4ce8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('teacher', 'image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'image',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('student', 'image',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
