"""added temporary_attendance table

Revision ID: 44a409621621
Revises: 6476a42af3c4
Create Date: 2025-03-14 15:45:36.488677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a409621621'
down_revision: Union[str, None] = '6476a42af3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_attendance_student_id'), 'temporary_attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_temporary_attendance_timetable_id'), 'temporary_attendance', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_attendance_timetable_id'), table_name='temporary_attendance')
    op.drop_index(op.f('ix_temporary_attendance_student_id'), table_name='temporary_attendance')
    op.drop_table('temporary_attendance')
    # ### end Alembic commands ###
