"""added attendance table

Revision ID: 497b3c7b99cf
Revises: 6662bd82713a
Create Date: 2025-04-01 15:43:38.654873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497b3c7b99cf'
down_revision: Union[str, None] = '6662bd82713a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('percentage', sa.Double(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lesson', sa.Column('credi', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lesson_credi'), 'lesson', ['credi'], unique=False)
    op.add_column('timetable', sa.Column('type', sa.Enum('TEORIC', 'PRACTIC', name='type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'type')
    op.drop_index(op.f('ix_lesson_credi'), table_name='lesson')
    op.drop_column('lesson', 'credi')
    op.drop_table('attendance')
    # ### end Alembic commands ###
