"""updated temporary db

Revision ID: 512ad1a8f575
Revises: 
Create Date: 2025-03-14 12:16:07.922221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512ad1a8f575'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('image', sa.String(), nullable=True))
    op.add_column('teacher', sa.Column('image', sa.String(), nullable=True))
    op.add_column('timetable', sa.Column('cabinet_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'cabinet_num')
    op.drop_column('teacher', 'image')
    op.drop_column('student', 'image')
    # ### end Alembic commands ###
