"""added relation btw timetable temporary db

Revision ID: 6476a42af3c4
Revises: d262ed89ed64
Create Date: 2025-03-14 15:37:12.750146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6476a42af3c4'
down_revision: Union[str, None] = 'd262ed89ed64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
