"""updated attendance

Revision ID: 68a45874c90c
Revises: eb4c13bdb45d
Create Date: 2025-04-04 13:26:13.346964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a45874c90c'
down_revision: Union[str, None] = 'eb4c13bdb45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'date')
    # ### end Alembic commands ###
