"""updated temporary db added image

Revision ID: 6c1bd0259eee
Revises: 497b3c7b99cf
Create Date: 2025-04-02 16:16:47.150419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1bd0259eee'
down_revision: Union[str, None] = '497b3c7b99cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_attendance', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_attendance', 'image')
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timetable_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='attendance_student_id_fkey'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name='attendance_timetable_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    # ### end Alembic commands ###
