"""Add one-to-one relation between user and teacher

Revision ID: b32fb63920b8
Revises: 7390dc644343
Create Date: 2025-02-18 12:27:04.916753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32fb63920b8'
down_revision: Union[str, None] = '7390dc644343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'student', ['user_id'])
    op.create_foreign_key(None, 'student', 'users', ['user_id'], ['id'])
    op.add_column('teacher', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'teacher', ['user_id'])
    op.create_foreign_key(None, 'teacher', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_constraint(None, 'teacher', type_='unique')
    op.drop_column('teacher', 'user_id')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'user_id')
    # ### end Alembic commands ###
