"""updated attendance db

Revision ID: b5fed9f31540
Revises: efc8a4babff3
Create Date: 2025-04-30 17:33:12.547412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fed9f31540'
down_revision: Union[str, None] = 'efc8a4babff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_timetable_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'timetable', ['timetable_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_timetable_id_fkey', 'attendance', 'timetable', ['timetable_id'], ['id'])
    # ### end Alembic commands ###
