"""added image to teacher and student

Revision ID: b9903aa4ce8e
Revises: 8a821db8c109
Create Date: 2025-03-04 15:46:39.857888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9903aa4ce8e'
down_revision: Union[str, None] = '8a821db8c109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('teacher', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'image')
    op.drop_column('student', 'image')
    # ### end Alembic commands ###
