"""added temporary db

Revision ID: e7d1591744c0
Revises: 093d744e71aa
Create Date: 2025-03-06 15:27:04.118534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d1591744c0'
down_revision: Union[str, None] = '093d744e71aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('cabinet_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'cabinet_num')
    # ### end Alembic commands ###
