"""updated attendance added attended field

Revision ID: efc8a4babff3
Revises: a434d20e2fb6
Create Date: 2025-04-30 15:47:16.146546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc8a4babff3'
down_revision: Union[str, None] = 'a434d20e2fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'attended')
    # ### end Alembic commands ###
